/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountConfigurationResponse {
    #[serde(rename = "clientConfigureTransaction", skip_serializing_if = "Option::is_none")]
    pub client_configure_transaction: Option<Box<models::ClientConfigureTransaction>>,
    /// The ID of the last Transaction created for the Account.
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<i32>,
}

impl AccountConfigurationResponse {
    pub fn new() -> AccountConfigurationResponse {
        AccountConfigurationResponse {
            client_configure_transaction: None,
            last_transaction_id: None,
        }
    }
}

