/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelOrderResponse {
    /// The ID of the most recent Transaction created for the Account
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<i32>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "orderCancelTransaction", skip_serializing_if = "Option::is_none")]
    pub order_cancel_transaction: Option<Box<models::OrderCancelTransaction>>,
}

impl CancelOrderResponse {
    pub fn new() -> CancelOrderResponse {
        CancelOrderResponse {
            last_transaction_id: None,
            related_transaction_ids: None,
            order_cancel_transaction: None,
        }
    }
}

