/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Candlestick : The Candlestick representation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Candlestick {
    /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "bid", skip_serializing_if = "Option::is_none")]
    pub bid: Option<Box<models::CandlestickData>>,
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<Box<models::CandlestickData>>,
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<Box<models::CandlestickData>>,
    /// The number of prices created during the time-range represented by the candlestick.
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<i32>,
    /// A flag indicating if the candlestick is complete. A complete candlestick is one whose ending time is not in the future.
    #[serde(rename = "complete", skip_serializing_if = "Option::is_none")]
    pub complete: Option<bool>,
}

impl Candlestick {
    /// The Candlestick representation
    pub fn new() -> Candlestick {
        Candlestick {
            time: None,
            bid: None,
            ask: None,
            mid: None,
            volume: None,
            complete: None,
        }
    }
}

