/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientConfigure : A ClientConfigure represents the configuration of an Account by a client.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientConfigure {
    /// The client-provided alias for the Account.
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// The margin rate override for the Account.
    #[serde(rename = "marginRate", skip_serializing_if = "Option::is_none")]
    pub margin_rate: Option<f64>,
}

impl ClientConfigure {
    /// A ClientConfigure represents the configuration of an Account by a client.
    pub fn new() -> ClientConfigure {
        ClientConfigure {
            alias: None,
            margin_rate: None,
        }
    }
}

