/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderRequest {
    /// The base Order specification used when requesting that an Order be created. Each specific Order-type extends this definition.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<serde_json::Value>,
}

impl CreateOrderRequest {
    pub fn new() -> CreateOrderRequest {
        CreateOrderRequest {
            order: None,
        }
    }
}

