/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstrumentType : The type of the Instrument
/// The type of the Instrument
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstrumentType {
    #[serde(rename = "CURRENCY")]
    Currency,
    #[serde(rename = "CFD")]
    Cfd,
    #[serde(rename = "METAL")]
    Metal,

}

impl std::fmt::Display for InstrumentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Currency => write!(f, "CURRENCY"),
            Self::Cfd => write!(f, "CFD"),
            Self::Metal => write!(f, "METAL"),
        }
    }
}

impl Default for InstrumentType {
    fn default() -> InstrumentType {
        Self::Currency
    }
}

