/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketOrderPositionCloseout : A MarketOrderPositionCloseout specifies the extensions to a Market Order when it has been created to closeout a specific Position.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketOrderPositionCloseout {
    #[serde(rename = "instrument", skip_serializing_if = "Option::is_none")]
    pub instrument: Option<models::InstrumentName>,
    /// Either \"ALL\", or a positive DecimalNumber reflection a partial unit
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
}

impl MarketOrderPositionCloseout {
    /// A MarketOrderPositionCloseout specifies the extensions to a Market Order when it has been created to closeout a specific Position.
    pub fn new() -> MarketOrderPositionCloseout {
        MarketOrderPositionCloseout {
            instrument: None,
            units: None,
        }
    }
}

