/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketOrderMarginCloseout : Details for the Market Order extensions specific to a Market Order placed that is part of a Market Order Margin Closeout in a client's account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketOrderMarginCloseout {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<models::MarketOrderMarginCloseoutReason>,
}

impl MarketOrderMarginCloseout {
    /// Details for the Market Order extensions specific to a Market Order placed that is part of a Market Order Margin Closeout in a client's account
    pub fn new() -> MarketOrderMarginCloseout {
        MarketOrderMarginCloseout {
            reason: None,
        }
    }
}

