/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderClientExtensionsModify : A OrderClientExtensionsModify represents the modification of an Order's Client Extensions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderClientExtensionsModify {
    /// The ID of the Order who's client extensions are to be modified.
    #[serde(rename = "orderID", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
    /// The original Client ID of the Order who's client extensions are to be modified.
    #[serde(rename = "clientOrderID", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    #[serde(rename = "clientExtensionsModify", skip_serializing_if = "Option::is_none")]
    pub client_extensions_modify: Option<Box<models::ClientExtensions>>,
    #[serde(rename = "tradeClientExtensionsModify", skip_serializing_if = "Option::is_none")]
    pub trade_client_extensions_modify: Option<Box<models::ClientExtensions>>,
}

impl OrderClientExtensionsModify {
    /// A OrderClientExtensionsModify represents the modification of an Order's Client Extensions.
    pub fn new() -> OrderClientExtensionsModify {
        OrderClientExtensionsModify {
            order_id: None,
            client_order_id: None,
            client_extensions_modify: None,
            trade_client_extensions_modify: None,
        }
    }
}

