/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PricingResponse {
    /// The list of Price objects requested.
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<models::ClientPrice>>,
    /// The list of home currency conversion factors requested. This field will only be present if includeHomeConversions was set to true in the request.
    #[serde(rename = "homeConversions", skip_serializing_if = "Option::is_none")]
    pub home_conversions: Option<Vec<models::HomeConversions>>,
    /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl PricingResponse {
    pub fn new() -> PricingResponse {
        PricingResponse {
            prices: None,
            home_conversions: None,
            time: None,
        }
    }
}

