/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RelatedTransaction : The definition of related transactions and the last transaction encapsulated in an object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedTransaction {
    /// The ID of the most recent Transaction created for the Account
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<i32>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Option<Vec<i32>>>,
}

impl RelatedTransaction {
    /// The definition of related transactions and the last transaction encapsulated in an object.
    pub fn new() -> RelatedTransaction {
        RelatedTransaction {
            last_transaction_id: None,
            related_transaction_ids: None,
        }
    }
}

