/*
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnitsAvailableDetails : Representation of many units of an Instrument are available to be traded for both long and short Orders.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnitsAvailableDetails {
    /// The units available for long Orders.
    #[serde(rename = "long", skip_serializing_if = "Option::is_none")]
    pub long: Option<f64>,
    /// The units available for short Orders.
    #[serde(rename = "short", skip_serializing_if = "Option::is_none")]
    pub short: Option<f64>,
}

impl UnitsAvailableDetails {
    /// Representation of many units of an Instrument are available to be traded for both long and short Orders.
    pub fn new() -> UnitsAvailableDetails {
        UnitsAvailableDetails {
            long: None,
            short: None,
        }
    }
}

